### ISSUE TITLE
decompilation errror on hello world for arm

### ISSUE THREAD

**Issue by radare** [radareorg/r2dec-js#200]
[hello-arm.zip](https://github.com/radareorg/r2dec-js/files/4086969/hello-arm.zip)

[a.json.zip](https://github.com/radareorg/r2dec-js/files/4086971/a.json.zip)

```
$ r2 -c 's main;af;pdd' a.out
r2dec has crashed (info: a.out @ 0x464).
Please report the bug at https://github.com/wargio/r2dec-js/issues
Use the option '--issue' or the command 'pddi' to generate
the needed data for the issue.
[0x00000464]> pddi > a.json
[0x00000464]> !op
```

**Comment by wargio** [comment]
fixed with https://github.com/radareorg/r2dec-js/commit/bb26e6b020778e11c6db4768215b0e9ee0a94469
