### ISSUE TITLE
FreeBSD cannot build r2dec

### ISSUE THREAD

**Issue by wargio** [radareorg/r2dec-js#214]
I will make release of the report in overall for the test results as per finish overall tests for current as discussed by @trufae , the image of the report is something [similar to this one](https://github.com/radareorg/r2jp/blob/master/UNIXServerCompatibilityReportEN.md) (the data is old, up to April tests only) but more thorough by adding embedded platforms and including ESIL as per discussed w @condret too. I am busy in upgrading servers, hypervisors or emulation instance for this purpose with overhaul a lot of host servers in IDC for this purpose (which was delayed do to Corona/Covid19 until June 1st re-opening).

The link above contains list of platform to test/support and not to support, and the tests or bug issue from me will be based on supported ones, this means the features, the installation, the built and compatibility up to continuous-built version.

@wargio Hi Gio. Yes, certainly will bring this up as issue, we are in the same page of what has to be supported and not. Just a quicky snip is as below:
```asm
$ r2pm update
HEAD is now at ef8733e Remove pyc (#101)
Updating ef8733e..1c4339a
Fast-forward
 db/r2taint | 16 ++++++++++++++++
 db/yara    |  2 +-
 2 files changed, 17 insertions(+), 1 deletion(-)
 create mode 100644 db/r2taint
Updating /home/test/.local/share/radare2/r2pm/db ...
Already up to date.
$ r2pm install r2dec
Already up to date.
Install Done For r2dec
cc  -I/home/test/.local/share/radare2/prefix/include -g -O3 -std=c99 -Wall -fPIC -I./duktape -c duktape/duktape.c -o duktape/duktape.o
cc  -I/home/test/.local/share/radare2/prefix/include -g -O3 -std=c99 -Wall -fPIC -I./duktape -c duktape/duk_console.c -o duktape/duk_console.o
duktape/duk_console.c:13:10: fatal error: 'r_cons.h' file not found
#include <r_cons.h>
         ^~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /usr/home/test/.local/share/radare2/r2pm/git/r2dec-js/p
$ uname -smor
FreeBSD 12.1-RELEASE-p1 amd64
$ date
Fri Jun 12 02:38:28 JST 2020
$ r2 -v
radare2 4.5.0-git 24737 @ freebsd-x86-64 git.4.4.0-253-gae883f0cd
commit: ae883f0cd3b12da0272f1471cab82c2e75cd1575 build: 2020-06-10__19:54:43
```

@XVilka yes, roger that, that is also goes to pdc matter. I'll  bring the issue up. Please give me time.

_Originally posted by @unixfreaxjp in https://github.com/radareorg/radare2/issues/17043#issuecomment-642826815_

**Comment by wargio** [comment]
Looks like the home is `/usr/home/test/` but r2dec is searching for `/home/test/.local/share/radare2/prefix/include` it might be a r2pm issue.

**Comment by unixfreaxjp** [comment]
@wargio I will check and testing the path you mention, thank you for the reply

**Comment by trufae** [comment]
how was r2 installed in the home? imho the issue is in how it was installed because this path is taken from pkg-config, so the problem is imho not in r2pm.

@unixfreaxjp can you show the output of `pkg-config --cflags --libs r_core`?

maybe good to know the value of $HOME as well as if sys/user.sh was used or differnet method that could lead to inconsistent pkgconfig files

**Comment by unixfreaxjp** [comment]
Hi @trufae    Thank's for quick response. I reply this one by one below:

> @unixfreaxjp can you show the output of `pkg-config --cflags --libs r_core`?
```asm
$ pkg-config --cflags --libs r_core
Package r_core was not found in the pkg-config search path.
Perhaps you should add the directory containing `r_core.pc'
to the PKG_CONFIG_PATH environment variable
Package 'r_core', required by 'virtual:world', not found
```
About pkg-config:
```
PKG-CONFIG(8)           FreeBSD System Manager's Manual          PKG-CONFIG(8)

NAME
     pkg config - retrieve the value of a given configuration option

SYNOPSIS
     pkg config name

DESCRIPTION
     pkg config retrieve the value of a given configuration option.  For
     lists, one line per entry will be printed, key/values will be printed as
     one line per key/value pair.
       :
```

> how was r2 installed in the home? 

**Condition:**
This is test machine so for testing purpose so I am using generic installation commands to setup after all of r2 instances were cleaned up firstly with `purge`, `uninstall`, `reset git`, etc. 
So no previous libraries, environments, git related data will be on the way for new version testing.  Case for xBSD tests I even making extra efforts to  re-cloned it beforehand.

So the step used is go to *re-cloned* directory under `$HOME` (see value below) and run the installation  command printed below as a test user with `sudo` support (just as if you expect on OSX)
```
sys/install.sh
```

> maybe good to know the value of `$HOME` as well

Here we go:
```
$ echo  $HOME 
/home/test
```

> as if `sys/user.sh` was used or different method that could lead to inconsistent pkgconfig files.

I understand your approach in confirming, no, I only use `sys/install.sh` in the newly re-cloned directory created under the  `$HOME` for tests.

Hope this helps.

**Comment by trufae** [comment]
I've found the issue. The package was poorly written and was using `make` instead of `${MAKE}`. The following commands should do the trick:

```
$ r2pm up
$ r2pm -ci r2dec
```

enjoy!

**Comment by unixfreaxjp** [comment]
@trufae Thank you! It works in all FreeBSD instances!!

I tested and using this fix below Hope to see PR.

> was using `make` instead of `${MAKE}`. 

And this "workaround" was tested too:
```
$ r2pm up
$ r2pm -ci r2dec
```

**Comment by wargio** [comment]
cool. thanks @trufae
